// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePostByIDs(ctx context.Context, arg DeletePostByIDsParams) error
	FindBookmarksByUserID(ctx context.Context, userID uuid.UUID) ([]Bookmark, error)
	FindPostByIDs(ctx context.Context, arg FindPostByIDsParams) (Post, error)
	FindPostsByAuthor(ctx context.Context, authorID uuid.UUID) ([]Post, error)
	FindUserByAuthID(ctx context.Context, authID string) (User, error)
	GetPosts(ctx context.Context, offset int32) ([]GetPostsRow, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
